### ISSUE TITLE
Xcode 8.1 build fail

### ISSUE THREAD

**Issue by EricCartman** [iException/BUKPhotoBrowser#2]
when build with Xcode 8.1, it fails with the following infomation:

CodeSign /Users/dangzhihua/Library/Developer/Xcode/DerivedData/Auction-fjxiqhhopoicvdcspszjifkowhsf/Build/Products/Debug-iphonesimulator/BUKPhotoBrowser.bundle
    cd /Users/dangzhihua/Projects/DacangJP/Auction/Pods
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/dangzhihua/Library/Developer/Xcode/DerivedData/Auction-fjxiqhhopoicvdcspszjifkowhsf/Build/Products/Debug-iphonesimulator/BUKPhotoBrowser.bundle

/Users/dangzhihua/Library/Developer/Xcode/DerivedData/Auction-fjxiqhhopoicvdcspszjifkowhsf/Build/Products/Debug-iphonesimulator/BUKPhotoBrowser.bundle: bundle format unrecognized, invalid, or unsuitable

please give some help, thanks.

**Comment by yimingtang** [comment]
Hi, I'm sorry for the late reply. It works well on my side. I'll close the issue if you've already solved the problem.
